server:
  port: 8086

spring:
  datasource:
    # Aquí especificamos el esquema en la URL para este microservicio
    url: jdbc:postgresql://${custom.database.host}:${custom.database.port}/${custom.database.name}?currentSchema=proveedor_schema&sslmode=require
  flyway:
    schemas: proveedor_schema
    default-schema: proveedor_schema