CREATE SCHEMA IF NOT EXISTS proveedor_schema;

CREATE TABLE IF NOT EXISTS proveedor_schema.proveedores (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255) NOT NULL,
    rut            VARCHAR(32)  NOT NULL,
    email          VARCHAR(255) NOT NULL,
    telefono       VARCHAR(50)  NOT NULL,
    direccion      VARCHAR(255) NOT NULL,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_proveedores_rut UNIQUE (rut),
    CONSTRAINT chk_email_formato CHECK (email LIKE '%@%.%'),
    CONSTRAINT chk_nombre_no_vacio CHECK (TRIM(nombre) != ''),
    CONSTRAINT chk_rut_no_vacio CHECK (TRIM(rut) != '')
);

CREATE INDEX idx_proveedores_rut    ON proveedor_schema.proveedores(rut);
CREATE INDEX idx_proveedores_activo ON proveedor_schema.proveedores(activo);
CREATE INDEX idx_proveedores_nombre ON proveedor_schema.proveedores(nombre);
