CREATE SCHEMA IF NOT EXISTS producto_schema;

CREATE TABLE IF NOT EXISTS producto_schema.productos (
    id           BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku          VARCHAR(255)      NOT NULL,
    nombre       VARCHAR(255)      NOT NULL,
    precio_base  DOUBLE PRECISION  NOT NULL,
    proveedor_id BIGINT            NOT NULL,
    activo       BOOLEAN           NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_productos_sku          UNIQUE (sku),
    CONSTRAINT chk_sku_no_vacio CHECK (TRIM(sku) != ''),
    CONSTRAINT chk_precio_base_positivo  CHECK  (precio_base > 0),
    CONSTRAINT chk_nombre_producto CHECK (TRIM(nombre) != '')
);

CREATE INDEX idx_productos_sku       ON producto_schema.productos(sku);
CREATE INDEX idx_productos_activo    ON producto_schema.productos(activo);
CREATE INDEX idx_productos_proveedor ON producto_schema.productos(proveedor_id);
