CREATE SCHEMA IF NOT EXISTS movimiento_schema;

CREATE TABLE IF NOT EXISTS movimiento_schema.movimientos (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id       BIGINT       NOT NULL,
    bodega_origen_id  BIGINT,
    bodega_destino_id BIGINT,
    tipo              VARCHAR(15)  NOT NULL,
    cantidad          INTEGER      NOT NULL,
    motivo            VARCHAR(255) NOT NULL,
    fecha             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_tipo_movimiento  CHECK (tipo IN ('ENTRADA', 'SALIDA', 'TRANSFERENCIA')),
    CONSTRAINT chk_cantidad_positiva CHECK (cantidad > 0),
    CONSTRAINT chk_transferencia_distinta CHECK (
        tipo != 'TRANSFERENCIA' 
        OR (
            bodega_origen_id IS NOT NULL
            AND bodega_destino_id IS NOT NULL
            AND bodega_origen_id != bodega_destino_id
        )
    )
);

ALTER TABLE movimiento_schema.movimientos
    ADD CONSTRAINT fk_movimientos_producto FOREIGN KEY (producto_id) REFERENCES producto_schema.productos(id) NOT VALID;

ALTER TABLE movimiento_schema.movimientos
    ADD CONSTRAINT fk_movimientos_bodega_origen FOREIGN KEY (bodega_origen_id) REFERENCES bodega_schema.bodegas(id) NOT VALID;

ALTER TABLE movimiento_schema.movimientos
    ADD CONSTRAINT fk_movimientos_bodega_destino FOREIGN KEY (bodega_destino_id) REFERENCES bodega_schema.bodegas(id) NOT VALID;

CREATE INDEX idx_movimientos_producto ON movimiento_schema.movimientos(producto_id);
CREATE INDEX idx_movimientos_tipo     ON movimiento_schema.movimientos(tipo);
CREATE INDEX idx_movimientos_origen   ON movimiento_schema.movimientos(bodega_origen_id);
CREATE INDEX idx_movimientos_destino  ON movimiento_schema.movimientos(bodega_destino_id);
CREATE INDEX idx_movimientos_fecha    ON movimiento_schema.movimientos(fecha);
