CREATE SCHEMA IF NOT EXISTS abastecimiento_schema;

CREATE TABLE IF NOT EXISTS abastecimiento_schema.ordenes_compra (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id   BIGINT       NOT NULL,
    estado         VARCHAR(20)  NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_oc_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECIBIDA', 'CANCELADA'))
);

CREATE TABLE IF NOT EXISTS abastecimiento_schema.detalle_orden_compra (
    id               BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_compra_id  BIGINT            NOT NULL,
    producto_id      BIGINT            NOT NULL,
    cantidad         INTEGER           NOT NULL,
    precio_unitario  DOUBLE PRECISION  NOT NULL,
    CONSTRAINT fk_detalle_orden_compra FOREIGN KEY (orden_compra_id)
        REFERENCES abastecimiento_schema.ordenes_compra(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_doc_cantidad_positiva    CHECK (cantidad > 0),
    CONSTRAINT chk_doc_precio_unitario_positivo   CHECK (precio_unitario > 0)
);

CREATE INDEX idx_oc_proveedor_id  ON abastecimiento_schema.ordenes_compra(proveedor_id);
CREATE INDEX idx_oc_estado        ON abastecimiento_schema.ordenes_compra(estado);
CREATE INDEX idx_doc_orden_compra ON abastecimiento_schema.detalle_orden_compra(orden_compra_id);
CREATE INDEX idx_doc_producto_id  ON abastecimiento_schema.detalle_orden_compra(producto_id);
